# Pages

pages:
    name: Pages
    singular_name: Page
    fields:
        name:
            type: text
            class: large
        template:
            type: templateselect

# Home

home:
    name: Home
    singular_name: Home Page
    default_status: published
    fields:
        name:
            type: text
            class: large
        title:
            type: text
            height: 300px
        subtitle:
            type: text
            height: 300px
        mission_statement:
            type: html
            height: 300px
        image:
            type: image
    record_template: index.twig

# News

news:
    name: News
    singular_name: News Item
    slug: news
    singular_slug: news
    listing_template: news.twig
    record_template: newsitem.twig
    default_status: published
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        excerpt:
            type: textarea
            height: 150px
        body:
            type: html
            height: 300px

# Board

board:
    name: Board
    singular_name: Board Member
    slug: board
    singular_slug: board
    listing_template: board.twig
    record_template: boardmember.twig
    default_status: published
    fields:
        name:
            type: text
            class: large
        slug:
            type: slug
            uses: name
        image:
            type: image
        body:
            type: html
            height: 300px

# ClinicsAndMeetings

ClinicsAndMeetings:
    name: Clinics And Meetings
    singular_name: Clinic Or Meeting
    slug: clinicsmeetings
    singular_slug: clinicormeeting
    listing_template: clinicsandmeetings.twig
    record_template: clinicormeeting.twig
    default_status: published
    fields:
        meeting:
            type: text
            class: large
        date_and_time:
            type: datetime
            height: large
        location:
            type: text
            height: large
        site:
            type: text
            height: large
        sport:
            type: select
            values: [ Basketball, Football ]
    sort: date_and_time ASC

#PromotionalPoints

PromotionalPoints:
    name: Promotional Points
    singular_name: Promotional Point
    slug: promotionalpoints
    singular_slug: promotionalpoint
    listing_template: promotionalpoints.twig
    default_status: published
    fields:
        text:
            type: html
            class: large

#RuleChanges

RuleChanges:
    name: Rule Changes
    singular_name: Rule Change
    slug: rulechanges
    singular_slug: rulechange
    listing_template: rulechanges.twig
    default_status: published
    fields:
        title:
            type: text
            class: large
        logo:
            type: image
        text:
            type: html
            class: large
        sport:
            type: select
            values: [ Basketball, Football ]
    sort: sport ASC

#Committees

Committees:
    name: Committees
    singular_name: Committee
    slug: committees
    singular_slug: committee
    listing_template: committees.twig
    default_status: published
    fields:
        committee:
            type: text
            class: large
        members:
            type: html
            class: large
    sort: committee ASC

#ConstitutionAndBylaws

ConstitutionAndBylaws:
    name: Constitution and Bylaws
    singular_name: Constitution Or Bylaw
    slug: constitutionandbylaws
    singular_slug: constitutionorbylaw
    listing_template: constitutionandbylaws.twig
    default_status: published
    fields:
        name:
            type: text
            class: large
        content:
            type: html
            class: large
    sort: name DESC

#SocialMediaPolicies

SocialMediaPolicies:
    name: Social Media Policies
    singular_name: Social Media Policy
    slug: socialmediapolicies
    singular_slug: socialmediapolicy
    listing_template: socialmediapolicies.twig
    default_status: published
    fields:
        content:
            type: html
            class: large

#Teams

Teams:
    name: Schools and Teams
    singular_name: School and Team
    slug: schoolsandteams
    singular_slug: schoolandteam
    listing_template: schoolsandteams.twig
    default_status: published
    fields:
        type_of_school:
            type: select
            values: [ High_School, Elem/Middle_School, Charter/Private_School, Youth_League ]
        school:
            type: text
            class: large
        address:
            type: text
            class: large
        city_state_zip:
            type: text
            class: large
        phone_number:
            type: text
            class: large
    sort: school ASC

#GameFees

GameFees:
    name: Game Fees
    singular_name: Game Fee
    slug: gamefees
    singular_slug: gamefee
    listing_template: gamefees.twig
    default_status: published
    fields:
        sport:
            type: select
            values: [ Football, Basketball ]
        content:
            type: html
            class: large
    sort: sport ASC

#Evaluations
Evaluations:
    name: Evaluations
    singular_name: Evaluation
    slug: evaluations
    singular_slug: evaluation
    listing_template: evaluations.twig
    default_status: published
    fields:
        name:
            type: text
            class: large

#Awards
Awards:
    name: Awards
    singular_name: Award
    slug: awards
    singular_slug: award
    listing_template: awards.twig
    default_status: published
    fields:
        title:
            type: text
            class: large
        content:
            type: html
            class: large
        sport:
            type: select
            values: [ Football, Basketball ]
    sort: sport ASC

#Pictures
Pictures:
    name: Pictures
    singular_name: Picture
    slug: pictures
    singular_slug: picture
    listing_template: pictures.twig
    record_template: picture.twig
    default_status: published
    fields:
        imagelist:
            type: imagelist

#Links
Links:
    name: Links
    singular_name: Link
    slug: links
    singular_slug: link
    listing_template: links.twig
    default_status: published
    fields:
        name:
            type: text
            class: large
        url:
            type: text
            class: large
        image:
            type: image
