# Pages

pages:
    name: Pages
    singular_name: Page
    fields:
        name:
            type: text
            class: large
        template:
            type: templateselect

# Home

home:
    name: Home
    singular_name: Home Page
    default_status: published
    fields:
        name:
            type: text
            class: large
        title:
            type: text
            height: 300px
        subtitle:
            type: text
            height: 300px
        mission_statement:
            type: html
            height: 300px
        image:
            type: image
    record_template: index.twig

# News

news:
    name: News
    singular_name: News Item
    slug: news
    singular_slug: news
    listing_template: news.twig
    record_template: newsitem.twig
    default_status: published
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        excerpt:
            type: textarea
            height: 150px
        body:
            type: html
            height: 300px

# Board

board:
    name: Board
    singular_name: Board Member
    slug: board
    singular_slug: board
    listing_template: board.twig
    record_template: boardmember.twig
    default_status: published
    fields:
        name:
            type: text
            class: large
        slug:
            type: slug
            uses: name
        image:
            type: image
        body:
            type: html
            height: 300px

# ClinicsAndMeetings

ClinicsAndMeetings:
    name: Clinics And Meetings
    singular_name: Clinic Or Meeting
    slug: clinicsmeetings
    singular_slug: clinicormeeting
    listing_template: clinicsandmeetings.twig
    record_template: clinicormeeting.twig
    default_status: published
    fields:
        meeting:
            type: text
            class: large
        date_and_time:
            type: datetime
            height: large
        location:
            type: text
            height: large
        site:
            type: text
            height: large
        sport:
            type: select
            values: [ Basketball, Football ]
    sort: date_and_time ASC

#PromotionalPoints

PromotionalPoints:
    name: Promotional Points
    singular_name: Promotional Point
    slug: promotionalpoints
    singular_slug: promotionalpoint
    listing_template: promotionalpoints.twig
    default_status: published
    fields:
        text:
            type: html
            class: large

#RuleChanges

RuleChanges:
    name: Rule Changes
    singular_name: Rule Change
    slug: rulechanges
    singular_slug: rulechange
    listing_template: rulechanges.twig
    default_status: published
    fields:
        title:
            type: text
            class: large
        logo:
            type: image
        text:
            type: html
            class: large
        sport:
            type: select
            values: [ Basketball, Football ]
    sort: sport ASC

#Committees

Committees:
    name: Committees
    singular_name: Committee
    slug: committees
    singular_slug: committee
    listing_template: committees.twig
    default_status: published
    fields:
        committee:
            type: text
            class: large
        members:
            type: html
            class: large
    sort: committee ASC

#ConstitutionAndBylaws

ConstitutionAndBylaws:
    name: Constitution and Bylaws
    singular_name: Constitution Or Bylaw
    slug: constitutionandbylaws
    singular_slug: constitutionorbylaw
    listing_template: constitutionandbylaws.twig
    default_status: published
    fields:
        name:
            type: text
            class: large
        content:
            type: html
            class: large
    sort: name DESC

#SocialMediaPolicies

SocialMediaPolicies:
    name: Social Media Policies
    singular_name: Social Media Policy
    slug: socialmediapolicies
    singular_slug: socialmediapolicy
    listing_template: socialmediapolicies.twig
    default_status: published
    fields:
        content:
            type: html
            class: large
