# Pages

pages:
    name: Pages
    singular_name: Page
    fields:
        name:
            type: text
            class: large
        template:
            type: templateselect

# Home

home:
    name: Home
    singular_name: Home Page
    default_status: published
    fields:
        name:
            type: text
            class: large
        title:
            type: text
            height: 300px
        subtitle:
            type: text
            height: 300px
        body:
            type: html
            height: 300px
        image:
            type: image
    record_template: index.twig

# News

news:
    name: News
    singular_name: News Item
    slug: news
    singular_slug: news
    listing_template: news.twig
    record_template: newsitem.twig
    default_status: published
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        excerpt:
            type: textarea
            height: 150px
        body:
            type: html
            height: 300px

# Board

board:
    name: Board
    singular_name: Board Member
    slug: board
    singular_slug: board
    listing_template: board.twig
    record_template: boardmember.twig
    default_status: published
    fields:
        name:
            type: text
            class: large
        slug:
            type: slug
            uses: name
        image:
            type: image
        body:
            type: html
            height: 300px
